### PR TITLE
Updating codeception version

### PR DESCRIPTION
**Pull request by davibennun**

### CODE REVIEW

**Comment by oprudkyi** [comment]
Hi, 
Thank you but it seems like codeception 2.2. hasn't been released. 
probably "~2.1" would work better as it will cover all versions up to 3.0 
https://getcomposer.org/doc/articles/versions.md

**Comment by davibennun** [comment]
Hi,
In my composer.json I required `"codeception/codeception": "^2.2"` this gets me the latest codeception release, 2.2.0-RC2 and it conflicted with your package: 

```
oprudkyi/codeception-events-scripting v1.0.3 requires codeception/codeception ~2.1.0 -> satisfiable by codeception/codeception[2.1.x-dev]
```

I solved it forking your package and updating the codeception version to `^2.2`

I suggest merging it and keeping this change unreleased because codeception 2.2 was not released yet, so I can pull your package inside my app using the `dev-master`

**Comment by davibennun** [comment]
Oh thank you, it just got merged

**Comment by oprudkyi** [comment]
sorry, I was incorrect. seems. it will work correctly anyway.  
Thank you

**Comment by davibennun** [comment]
Hmm... looks like the composer tilde operator doesn't get RC versions.

**Pull request merged**
